# fly.toml app configuration file generated for mabar-discord-bot on 2024-08-24T19:41:59+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mabar-discord-bot'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.22.4'

[env]
  PORT = '8080'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
